name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install '.[test]'
    - name: Create temp folder
      id: temp_dir_setup
      run: |
        export TEMP_DIR="${{ runner.temp }}/my-temp-dir"
        mkdir -p "$TEMP_DIR"
        echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV
        echo "Temporary folder created: $TEMP_DIR"
    - name: Run tests
      run: |
        echo "Using temporary directory: $TEMP_DIR"
        pytest --temp-folder "$TEMP_DIR"
      env:
        TEMP_DIR: ${{ env.TEMP_DIR }}
    - name: Clean up temp folder
      if: always()
      run: |
        # Remove the temporary directory
        echo "Cleaning up temporary directory: $TEMP_DIR"
        rm -rf "$TEMP_DIR"
        